### ISSUE TITLE
Calendar viz won't work if there's a null date

### ISSUE THREAD

**Issue by snarron** [looker/visualization-api-examples#60]
What happens:
![explore__1__ads_and_orders](https://user-images.githubusercontent.com/1812779/33973641-d6d44f44-e038-11e7-8f2d-f46ba0ef0614.png)

Console error message:
![explore__1__ads_and_orders](https://user-images.githubusercontent.com/1812779/33973637-ce9f75ec-e038-11e7-90c7-eefdcfc391dc.png)

What should happen:
![explore__1__ads_and_orders](https://user-images.githubusercontent.com/1812779/33973658-e0fc1a42-e038-11e7-982f-4dfd326e5a29.png)

**Comment by snarron** [comment]
@jdavidson

**Comment by jdavidson** [comment]
A null in the date results will kill the visualization.

**Comment by jdavidson** [comment]
fixed by https://github.com/looker/visualization-api-examples/pull/61
